encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.wikipage, name="wikipage"),
    path("search", views.new_search, name="search"),
    path("add_entry", views.add_view, name='add_entry'),
    path("edit_entry/<str:title>", views.edit_entry, name='edit'),
    path("random", views.random_wiki, name="random_wiki")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render, redirect
from markdown2 import Markdown
from django.http import HttpResponseRedirect
from django import forms
from django.views.generic.edit import UpdateView
import random

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def wikipage(request,title):
    entry = util.get_entry(title)
    markdowner = Markdown()
    md_entry = markdowner.convert(entry)

    return render(request, "encyclopedia/wikipage.html", {
        "content": md_entry,
        "wikientry": title
        })

def new_search(request):
    searches = request.POST.get('q')
    entries = util.list_entries()
    search_result = []


    for entry in entries:
        if searches.lower() in entry.lower():
            search_result.append(entry)
        else:
            pass


    return render(request, "encyclopedia/search.html", {"search_result" : search_result})

class AddForm(forms.Form):
    title = forms.CharField(max_length=20)
    content = forms.CharField(widget=forms.Textarea)

def add_view(request):
    entries = util.list_entries()
    entries = [entry.lower() for entry in entries]
    errors = []
    if request.method == 'POST':
        form = AddForm(request.POST)
        title = form['title'].value()

        if title.lower() in entries:
            error = "Already Available Data"
            errors.append(error)

        else:
            if form.is_valid():
                title = form.cleaned_data['title']
                content = form.cleaned_data['content']
                util.save_entry(title, content)
            else:
                form = AddForm()

            return HttpResponseRedirect('/')
    else:
        form = AddForm()

    return render(request, "encyclopedia/add_new.html", {"form" : form, "errors": errors})

class EditForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea)

def edit_entry(request, title):
    entry = util.get_entry(title)
    if request.method == 'GET':
        form = EditForm(initial={'content' : entry})

    if request.method == 'POST':
        form = EditForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']
            util.save_entry(title, content)
        return HttpResponseRedirect('/')

    return render(request, "encyclopedia/edit.html", {"form":form, "title":title})

def random_wiki(request):
    entries = util.list_entries()
    number = len(entries) - 1
    rand_entry_index = random.randint(0, number)
    random_entry = entries[rand_entry_index]
    random_content = util.get_entry(random_entry)
    markdowner = Markdown()
    md_entry = markdowner.convert(random_content)

    return render(request, "encyclopedia/wikipage.html", {
        "content": md_entry,
        "wikientry": random_entry
        })

encyclopedia/templates/encyclopedia/add_new.html
{% extends "encyclopedia/layout.html" %}

{% load crispy_forms_tags %}

{% block body %}
<div class="main">
  {% for error in errors %}
  <div class="alert alert-danger" role="alert">
  {{ error }}
</div>
  {% endfor %}
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" name="submit" class="btn btn-primary">Submit</button>
</form>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% load crispy_forms_tags %}

{% block body %}
<div class="main">
  <h3>Title : {{ title }}</h3>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" name="submit" class="btn btn-primary">Submit</button>
</form>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <a href="{% url 'encyclopedia:wikipage' entry.title %}"><li>{{ entry }}</li></a>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="post" action='{% url 'encyclopedia:search' %}'>
                {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add_entry' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random_wiki' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% if search_result %}
            {% for search in search_result %}
                <a href="{% url 'encyclopedia:wikipage' search.title %}"><li>{{ search }}</li></a>
            {% endfor %}
        {% endif %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/wikipage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
  {{ wikientry|title }}
{% endblock %}

{% block body %}
  <h3>{{ content|safe }}</h3>
  <a href="{% url 'encyclopedia:edit' wikientry %}" class="btn btn-primary">Edit Content</a>
{% endblock %}